import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const mona = localFont({
  src: [
    {
      path: "../public/fonts/Mona-Sans-Light.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/Mona-Sans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Mona-Sans-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Mona-Sans-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mona.className}>{children}</body>
    </html>
  );
}
